import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Calendar, Target, Dumbbell, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import LogWorkout from "./LogWorkout";

export default function TrainingPlan() {
  const navigate = useNavigate();
  const [activeExercise, setActiveExercise] = useState<any>(null);

  const { data: activePlan, isLoading, refetch } = useQuery({
    queryKey: ['active-training-plan'],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Step 1: Get active assigned plan
      const { data: assigned, error: assignError } = await supabase
        .from('assigned_training_plans')
        .select(`
          *,
          training_plans (
            id,
            name,
            description,
            duration_weeks,
            is_ai_generated,
            ai_metadata
          )
        `)
        .eq('client_id', user.id)
        .eq('status', 'active')
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle();

      if (assignError) {
        console.error('[TrainingPlan] Error fetching assigned plan:', assignError);
        return null;
      }
      if (!assigned) return null;

      // Step 2: Get workouts for this plan
      const { data: workouts, error: workoutsError } = await supabase
        .from('training_plan_workouts')
        .select('*')
        .eq('plan_id', assigned.training_plans.id)
        .order('day_of_week', { ascending: true });

      if (workoutsError) {
        console.error('[TrainingPlan] Error fetching workouts:', workoutsError);
        throw workoutsError;
      }

      return {
        ...assigned,
        plan: assigned.training_plans,
        workouts: workouts || []
      };
    }
  });

  // Get today's logged workouts for progress tracking
  const { data: todayLogs, refetch: refetchLogs } = useQuery({
    queryKey: ['today-workout-logs'],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return [];

      const today = new Date().toISOString().split('T')[0];
      const { data } = await supabase
        .from('workout_logs')
        .select('exercise_name, set_number')
        .eq('user_id', user.id)
        .gte('performed_at', today)
        .lte('performed_at', today + 'T23:59:59');

      return data || [];
    },
    enabled: !!activePlan
  });

  const { data: preferences } = useQuery({
    queryKey: ['ai-preferences'],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return null;

      const { data } = await supabase
        .from('ai_training_preferences')
        .select('*')
        .eq('user_id', user.id)
        .single();

      return data;
    }
  });

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-48 w-full" />
        <Skeleton className="h-96 w-full" />
      </div>
    );
  }

  // No active plan - show onboarding
  if (!activePlan) {
    return (
      <>
        <Card className="border-dashed">
          <CardHeader className="text-center pb-4">
            <div className="mx-auto w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
              <Sparkles className="w-6 h-6 text-primary" />
            </div>
            <CardTitle>AI-Powered Training Plan</CardTitle>
            <CardDescription>
              Get a personalized training program generated by our AI coach
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center gap-4 pt-0">
            <ul className="space-y-2 text-sm text-muted-foreground max-w-md">
              <li className="flex items-start gap-2">
                <Target className="w-4 h-4 mt-0.5 text-primary" />
                <span>Customized to your goals and experience level</span>
              </li>
              <li className="flex items-start gap-2">
                <Calendar className="w-4 h-4 mt-0.5 text-primary" />
                <span>12-week periodized program with progressive overload</span>
              </li>
              <li className="flex items-start gap-2">
                <Dumbbell className="w-4 h-4 mt-0.5 text-primary" />
                <span>Tailored to your available equipment</span>
              </li>
            </ul>
            <Button 
              size="lg" 
              className="mt-4"
              onClick={() => navigate('/workouts/ai-onboarding')}
            >
              <Sparkles className="w-4 h-4 mr-2" />
              Generate My Training Plan
            </Button>
          </CardContent>
        </Card>
      </>
    );
  }

  // Show active plan
  const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const workoutsByDay = activePlan.workouts.reduce((acc, workout) => {
    if (!acc[workout.day_of_week]) {
      acc[workout.day_of_week] = [];
    }
    acc[workout.day_of_week].push(workout);
    return acc;
  }, {} as Record<number, any[]>);

  // Calculate exercise completion for today
  const getExerciseCompletion = (exerciseName: string) => {
    if (!todayLogs) return { completed: false, setsLogged: 0 };
    const logs = todayLogs.filter(log => log.exercise_name === exerciseName);
    return {
      completed: logs.length > 0,
      setsLogged: logs.length
    };
  };

  // Calculate today's progress
  const todayWorkouts = activePlan.workouts.filter(w => w.day_of_week === new Date().getDay());
  const totalExercisesToday = todayWorkouts.reduce((sum, w) => {
    const exercises = Array.isArray(w.exercises) ? w.exercises : [];
    return sum + exercises.length;
  }, 0);
  const completedExercisesToday = todayWorkouts.reduce((sum, w) => {
    const exercises = Array.isArray(w.exercises) ? w.exercises : [];
    return sum + exercises.filter((ex: any) => getExerciseCompletion(ex.name).completed).length;
  }, 0);
  const progressPercent = totalExercisesToday > 0 ? (completedExercisesToday / totalExercisesToday) * 100 : 0;

  return (
    <div className="space-y-6">
      {/* Plan Header */}
      <Card className={activePlan.plan?.is_ai_generated ? "border-primary" : ""}>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                {activePlan.plan?.is_ai_generated && (
                  <Sparkles className="w-5 h-5 text-primary" />
                )}
                {activePlan.plan?.name}
              </CardTitle>
              <CardDescription className="mt-2">
                {activePlan.plan?.description}
              </CardDescription>
            </div>
            {activePlan.plan?.is_ai_generated && (
              <Badge variant="secondary" className="shrink-0">
                <Sparkles className="w-3 h-3 mr-1" />
                AI Generated
              </Badge>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex gap-4 text-sm text-muted-foreground">
            <span className="flex items-center gap-1">
              <Calendar className="w-4 h-4" />
              {activePlan.plan?.duration_weeks} weeks
            </span>
            <span className="flex items-center gap-1">
              <Dumbbell className="w-4 h-4" />
              {activePlan.workouts.length} workouts
            </span>
          </div>

          {/* Today's Progress */}
          {totalExercisesToday > 0 && (
            <div className="space-y-2 pt-4 border-t">
              <div className="flex items-center justify-between text-sm">
                <span className="font-medium">Today's Progress</span>
                <span className="text-muted-foreground">
                  {completedExercisesToday}/{totalExercisesToday} exercises
                </span>
              </div>
              <Progress value={progressPercent} className="h-2" />
            </div>
          )}
        </CardContent>
      </Card>

      {/* Weekly Schedule */}
      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Weekly Schedule</h2>
        <div className="grid gap-4">
          {Object.entries(workoutsByDay).map(([day, workouts]) => (
            <Card key={day}>
              <CardHeader>
                <CardTitle className="text-lg">{dayNames[parseInt(day)]}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {workouts.map((workout, idx) => (
                  <div key={idx} className="space-y-2">
                    <h3 className="font-semibold">{workout.workout_name}</h3>
                    <div className="space-y-2">
                      {workout.exercises?.map((exercise: any, exerciseIdx: number) => {
                        const completion = getExerciseCompletion(exercise.name);
                        return (
                          <div key={exerciseIdx} className="flex items-center justify-between gap-2 py-2 border-b last:border-0">
                            <div className="flex items-center gap-2 flex-1">
                              {completion.completed && (
                                <CheckCircle2 className="w-4 h-4 text-primary shrink-0" />
                              )}
                              <div className="flex-1">
                                <div className="font-medium">{exercise.name}</div>
                                <div className="text-xs text-muted-foreground">
                                  {exercise.sets}×{exercise.reps} @ RPE {exercise.rpe}
                                  {completion.setsLogged > 0 && (
                                    <span className="ml-2">({completion.setsLogged} sets logged)</span>
                                  )}
                                </div>
                              </div>
                            </div>
                            <Button 
                              size="sm" 
                              variant={completion.completed ? "outline" : "default"}
                              onClick={() => setActiveExercise({
                                ...exercise,
                                dayOfWeek: parseInt(day),
                                workoutName: workout.workout_name
                              })}
                            >
                              {completion.completed ? "Log More" : "Log Workout"}
                            </Button>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Log Workout Sheet */}
      <Sheet open={!!activeExercise} onOpenChange={() => setActiveExercise(null)}>
        <SheetContent side="bottom" className="h-[90vh] overflow-y-auto">
          <SheetHeader>
            <SheetTitle>Log Exercise</SheetTitle>
          </SheetHeader>
          {activeExercise && (
            <div className="mt-6">
              <LogWorkout 
                exercise={activeExercise}
                assignedPlanId={activePlan.id}
                dayOfWeek={activeExercise.dayOfWeek}
                workoutName={activeExercise.workoutName}
                onComplete={() => {
                  setActiveExercise(null);
                  refetchLogs();
                  toast.success("Exercise completed!");
                }}
              />
            </div>
          )}
        </SheetContent>
      </Sheet>
    </div>
  );
}
