// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeStorage } from '@/lib/safeStorage';

const SUPABASE_URL = "https://d.elite10.club";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVleWttbXptZ3V6anBwZHVkdmVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTAwNjEsImV4cCI6MjA3NDAyNjA2MX0.nSc_MFoU6rAsyw0c8Mv-BD0MPuGAsuDXUckvMUyYX94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase: ReturnType<typeof createClient<Database>>;

try {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: safeStorage as any,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  console.log('✅ [Supabase] Client initialized successfully');
} catch (error) {
  console.error('💥 [Supabase] Failed to initialize client:', error);
  throw error;
}

export { supabase };